# Generated by Django 3.1.7 on 2021-11-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_superadmin',
            field=models.CharField(default=True, max_length=25),
        ),
    ]
