# Generated by Django 3.1.7 on 2022-02-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_topic_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
    ]
